version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    networks:
      - mern
  server:
    build: ./server
    ports:
      - "8000:8000"
    networks: 
      - mern
    depends_on:
      - database
  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mern
    volumes:
      - data:/data/db

networks:
  mern: 
    driver: bridge

volumes:
  data:
    driver: local
