version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "80"
    networks:
      - mern
  server:
    build: ./server
    ports:
      - "8000"
    networks: 
      - mern
    env_file:
      - ./server/.env
    
  
networks:
  mern: 
    driver: bridge

volumes:
  data:
    driver: local
